name: Application Pipeline; build, test and deploy the greetings application
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
    - hello-world/**
  pull_request:
    branches: [main]
    paths:
    - hello-world/**

defaults:
  run:
    working-directory: ./hello-world

jobs:
  compile-test-build-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14
    - name: Build jar with Maven
      run: mvn clean install
    - name: Build Container Image
      run: docker build --tag ghcr.io/lukonjun/hello-world:${{ github.run_id }} .
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Run docker push
      run: docker push ghcr.io/lukonjun/hello-world:${{ github.run_id }}
      
