name: Application Pipeline; build, test and deploy the greetings application
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
    - hello-world/**
  pull_request:
    branches: [main]
    paths:
    - hello-world/**

defaults:
  run:
    working-directory: ./hello-world

jobs:
  compile-test-build-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14
    - name: Build jar with Maven
      run: mvn clean install
    - name: Build Container Image
      run: docker build --tag ghcr.io/lukonjun/hello-world:${{ github.run_id }} .
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Run docker push
      run: docker push ghcr.io/lukonjun/hello-world:${{ github.run_id }}
      
  deploy-to-infrastructure:
    runs-on: ubuntu-latest
    needs:
      - compile-test-build-push
    steps:
    - uses: actions/checkout@v2
    - name: create file with ssh key
      run: |
        mkdir ~/.ssh
        touch ~/.ssh/id_rsa
        echo '${{ secrets.AWS_PRIVATE_KEY }}' >> ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: run ansible script 
      run: ansible-playbook -i hosts deploy_images.yml --extra-vars "token=${{ secrets.UPLOAD_IMAGE_TOKEN }}"
      working-directory: ./ansible
